//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace CarSensor
{
	public class Sensor : IEquatable<Sensor>
	{
		public int index;
		public float distance;
		public Vector2 angles;
		public Vector3 direction;
		public float theta;
		public bool detectsObstacle;
		public int obstacleIndex;

		public int runsWithDetection;
		public int age; //runs sensor has persisted


		public Sensor (float dist, Vector2 ang, Vector3 dir, float theta_)
		{
			distance = dist;
			angles = ang;
			direction = dir;
			theta = theta_;
			index = -1;

			detectsObstacle = false;
			obstacleIndex = -1;
			runsWithDetection = 0;
			age = 0;
		}


		public Sensor (float dist, Vector2 ang, Vector3 dir, float theta_, int ind) : this(dist, ang, dir, theta_)
		{
			index = ind;
			detectsObstacle = false;
			obstacleIndex = -1;

			runsWithDetection = 0;
			age = 0;
		}

		public Sensor(float dist, Vector2 ang, Vector3 dir, float theta_, bool detects, int ind, int oi) : this(dist, ang, dir, theta_, ind)
		{
			detectsObstacle = detects;
			obstacleIndex = oi;

			runsWithDetection = 0;
			age = 0;
		}

		public void setIndex(int index) {
			this.index = index;
		}

		public void detects(int obstacle) {
			detectsObstacle = true;
			obstacleIndex = obstacle;
		}

		public void detectedForThisRun() {
			runsWithDetection++;
		}

		public void increaseAge() {
			age++;
		}

		public string ToString() {
			return (distance + angles.x + angles.y + direction.x + direction.y + direction.z).ToString();
		}

		public bool Equals(Sensor other) {
			return this.angles == other.angles && this.distance == other.distance && this.direction == other.direction;
		}
	}

}

